language: python
python:
  - "2.7.13"
# command to install dependencies
install:
  - pip3 install homeassistant
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
