language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - cd /home/homeassistant/.homeassistant
  - source /srv/homeassistant/homeassistant_venv/bin/activate
  - hass --script check_config
