language: python
python:
  - "3.5.3"
install:
  - pip3 install homeassistant
script:
  - sudo /srv/homeassistant/bin/hass --script check_config -c /home/homeassistant/.homeassistant
before_install:
- mv travis_secrets.yaml secrets.yaml
