- platform: mjpeg
  mjpeg_url: http://192.168.0.24:6779/video
  name: Phonecam
  username: neil
  password: !secret cam_password
  
- platform: yi
  name: Front Door
  host: '192.168.0.21'
  password: !secret yihome
  ffmpeg_arguments: '-vf scale=800:450'
  
- platform: yi
  name: Garden
  host: '192.168.0.22'
  password: !secret yihome
  ffmpeg_arguments: '-vf scale=800:450'

#### Traffic Cams ###
# camera 2
- platform: generic
  name: M27 Jcn 3
  still_image_url: https://ichef.bbci.co.uk/traveluk/ha/19111/large
    
# camera 3
- platform: generic
  name: M27 to M3
  still_image_url: https://ichef.bbci.co.uk/traveluk/ha/12178/large
    
# camera 4
- platform: generic
  name: M3 Chandlers Ford
  still_image_url: https://ichef.bbci.co.uk/traveluk/ha/12156/large
    
# camera 5
- platform: generic
  name: M3 Twyford
  still_image_url: https://ichef.bbci.co.uk/traveluk/ha/12077/large
  
# camera 6
- platform: generic
  name: M3 J12 Eastleigh
  still_image_url: https://ichef.bbci.co.uk/traveluk/ha/12126/large

- platform: generic
  still_image_url: http://www.meteox.co.uk/images.aspx?jaar=-3&voor=&soort=loop-bliksem&c=&n=&tijdid=20091121831%20alt=
  name: Rain Radar

- platform: generic
  still_image_url: http://virga.sfsu.edu/gif/jetstream_atl_loop.gif
  name: Jetstream