alias: 'Water Temp Cold'
trigger:
- platform: numeric_state
  entity_id: sensor.water_temperature
  below: 40
- platform: time
  at: '06:00:00'
action:
- service: homeassistant.turn_off
  entity_id: switch.red
- service: homeassistant.turn_off
  entity_id: switch.green
- service: homeassistant.turn_on
  entity_id: switch.blue