alias: 'Water Temp Hot'
trigger:
  platform: numeric_state
  entity_id: sensor.water_temperature
  above: 50
action:
- service: homeassistant.turn_off
  entity_id: switch.green
- service: homeassistant.turn_off
  entity_id: switch.blue
- service: homeassistant.turn_on
  entity_id: switch.red