alias: 'Water Temp Hot'
trigger:
  platform: numeric_state
  entity_id: sensor.water_temperature
  above: 50
condition:
  condition: time
  after: '06:00:00'
  before: '22:30:00'
action:
- service: homeassistant.turn_off
  entity_id: switch.green
- service: homeassistant.turn_off
  entity_id: switch.blue
- service: homeassistant.turn_on
  entity_id: switch.red