alias: 'Water Temp Warm'
trigger:
  platform: numeric_state
  entity_id: sensor.water_temperature
  above: 41
  below: 49.9
action:
- service: homeassistant.turn_off
  entity_id: switch.red
- service: homeassistant.turn_off
  entity_id: switch.blue
- service: homeassistant.turn_on
  entity_id: switch.green