######### Water Temperature LED on 06:00 ############

alias: Water Temperature LED on 06:00
trigger:
  platform: time
  at: '06:00'
condition:
  condition: numeric_state
  entity_id: sensor.water_temperature
  above: 40
action:
    service: homeassistant.turn_on
    entity_id: switch.green